[package]
name = "subdomainbrute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.8"
rand = "0.8.5"
reqwest = "0.11.14"
tokio = "1.26.0"
futures = "0.3"
threadpool = "1.0"